version: '3'
services:
  test-db:
    container_name: test_db
    image: postgres:latest
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=test_db
