import { User } from 'src/pg/user/entities/user.entity';

export const userStub = {
  id: 1,
  name: 'John Doe',
  email: 'johndoe@example.com',
  password: 'hashedPassword',
  username: 'johndoe',
  profilePicUrl: null,
  newMessagePopup: true,
  unreadMessage: false,
  unreadNotification: false,
  role: 'user',
  resetToken: null,
  expireToken: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  bio: 'I am John Doe',
  facebook: 'johndoe_facebook',
  youtube: 'johndoe_youtube',
  twitter: 'johndoe_twitter',
  instagram: 'johndoe_instagram',
};

export const userStub2 = {
  id: 2,
  name: 'John Doe',
  email: 'johndoe2@example.com',
  password: 'hashedPassword',
  username: 'johndoe2',
  profilePicUrl: null,
  newMessagePopup: true,
  unreadMessage: false,
  unreadNotification: false,
  role: 'user',
  resetToken: 'someresettoken',
  expireToken: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  bio: 'I am John Doe',
  facebook: 'johndoe_facebook',
  youtube: 'johndoe_youtube',
  twitter: 'johndoe_twitter',
  instagram: 'johndoe_instagram',
};

export const userStub3 = {
  id: 3,
  name: 'Jane Doe',
  email: 'janedoe3@example.com',
  password: 'hashedPassword',
  username: 'janedoe',
  profilePicUrl: null,
  newMessagePopup: true,
  unreadMessage: false,
  unreadNotification: false,
  role: 'user',
  resetToken: 'someresettoken',
  expireToken: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  bio: 'I am John Doe',
  facebook: 'janedoe_facebook',
  youtube: 'janedoe_youtube',
  twitter: 'janedoe_twitter',
  instagram: 'janedoe_instagram',
};
